/*------------------------------------------------------------
SUPPRESSION et CREATION DES TABLES DE LA BASE : CREATEBD.sql
------------------------------------------------------------*/
SET ECHO OFF
PROMPT Suppression des tables 
DROP TABLE EMPLOYE      CASCADE CONSTRAINTS 
/
DROP TABLE DEPARTEMENT  CASCADE CONSTRAINTS 
/
DROP TABLE PROJET       CASCADE CONSTRAINTS 
/
DROP TABLE TRAVAILLER   CASCADE CONSTRAINTS 
/

PROMPT Création table EMPLOYE
CREATE TABLE EMPLOYE
(
          MATRICULE NUMBER(4),
	  ENOM VARCHAR2(30),
	  FONCTION VARCHAR2(30),
	  DATEREC DATE,
	  SALAIRE NUMBER(8,3),
	  COMMISSION NUMBER(8,3),
	  NUMDEPT NUMBER(2)
)
/

PROMPT Création table DEPARTEMENT
CREATE TABLE DEPARTEMENT
(
           NUMDEPT NUMBER(2),
           DNOM VARCHAR2(40),
           LOCALITE VARCHAR2(30)
)
/ 

PROMPT Création table PROJET
CREATE TABLE PROJET
(
           NUMPROJ NUMBER(3),
           PNOM VARCHAR2(40),
           EMPLACEMENT VARCHAR2(30)
)
/ 

PROMPT Création table TRAVAILLER
CREATE TABLE TRAVAILLER
(
           MATRICULE NUMBER(4),
           NUMPROJ NUMBER(3),
           NBRE_H NUMBER(5)
)
/ 
SET ECHO ON
