/*------------------------------------------------------------
CHARGEMENT DE LA BASE : INSERTION_BD.sql
-------------------------------------------------------------*/

/*==============================*/
/* Chargement Table DEPARTEMENT */
/*==============================*/
SET ECHO OFF
PROMPT	Chargement table DEPARTEMENT
INSERT INTO DEPARTEMENT VALUES (10,'FINANCE','PARIS')
/
INSERT INTO DEPARTEMENT VALUES (20,'ADMINISTRATIF','BRUXELLES')
/
INSERT INTO DEPARTEMENT VALUES (30,'TECHNIQUE','LONDRES')
/
INSERT INTO DEPARTEMENT VALUES (40,'OPERATIONNEL','ATHENES')
/

/*=========================*/
/* Chargement Table PROJET */
/*=========================*/

PROMPT	Chargement table PROJET
INSERT INTO PROJET  VALUES (10,'CONSTRUCTION D"UN CENTRE','PARIS')  	
/
INSERT INTO PROJET  VALUES (20,'PROGRAMME ROUTE DE L"EAU','BENIN')  	
/
INSERT INTO PROJET  VALUES (30,'ALIMENTATION EN EAU POTABLE','HAITI')  	
/
INSERT INTO PROJET  VALUES (40,'FORAGE PUITS','MADAGASCAR')  	
/
INSERT INTO PROJET  VALUES (50,'MAINTENANCE AERONAUTIQUE','LONDRES')  	
/

/*============================*/
/* Chargement Table EMPLOYE   */
/*============================*/

PROMPT	Chargement table EMPLOYE
INSERT INTO EMPLOYE VALUES 
(7800, 'THOMAS', 'PRESIDENT', TO_DATE('20-10-1980','dd-mm-yyyy'), 5000, null, 20)
/
INSERT INTO EMPLOYE VALUES 
(7600, 'BLAKE', 'MANAGER', TO_DATE('10-6-1981','dd-mm-yyyy'), 2850, null, 30)
/
INSERT INTO EMPLOYE VALUES 
(7780, 'CLARK', 'MANAGER', TO_DATE('13-9-1985','dd-mm-yyyy'), 2450, null, 10
)
/
INSERT INTO EMPLOYE VALUES 
(7566, 'JONES', 'MANAGER', TO_DATE('12-4-1990','dd-mm-yyyy'), 2975, null, 10)
/
INSERT INTO EMPLOYE VALUES 
(7788, 'SCOTT', 'ANALYSTE', TO_DATE('13-07-1997','dd-mm-rr'), 3000, 200, 30)
/
INSERT INTO EMPLOYE VALUES
(7902, 'LOLA', 'SECRÉTAIRE', TO_DATE('23-02-2005','dd-mm-yyyy'), 1750, null, 20)
/
INSERT INTO EMPLOYE VALUES 
(7450, 'SMITH', 'AGENT',  TO_DATE('7-2-2010','dd-mm-yyyy'), 800, null, 40)
/
/*=============================*/
/* Chargement Table TRAVAILLER */
/*=============================*/
PROMPT	Chargement table TRAVAILLER
INSERT INTO TRAVAILLER VALUES (7600, 30, 50)
/
INSERT INTO TRAVAILLER VALUES (7450, 20,100)
/
INSERT INTO TRAVAILLER VALUES (7600, 20,20)
/
INSERT INTO TRAVAILLER VALUES (7780, 10,150)
/
INSERT INTO TRAVAILLER VALUES (7902, 10,200)
/
INSERT INTO TRAVAILLER VALUES (7600, 10,30)
/
INSERT INTO TRAVAILLER VALUES (7566, 50,400)
/
INSERT INTO TRAVAILLER VALUES (7800, 40,120)
/
INSERT INTO TRAVAILLER VALUES (7902, 50,220)
/
INSERT INTO TRAVAILLER VALUES (7600, 40,35)
/
INSERT INTO TRAVAILLER VALUES (7566, 30,40)
/
COMMIT
/
SET ECHO ON
