-- erreur_predf3.sql
SET SERVEROUTPUT ON 

BEGIN

   INSERT INTO PROJET
   VALUES(10,'CONSTRUCTION D"UN CENTRE','PARIS');  	
   EXCEPTION
   WHEN DUP_VAL_ON_INDEX THEN
       DBMS_OUTPUT.PUT_LINE('Projet existe déjà');

END;
/
