-- derive_commission.sql
CREATE or REPLACE TRIGGER derive_commission
BEFORE UPDATE OR INSERT OF SALAIRE, FONCTION ON EMPLOYE
FOR EACH ROW 
WHEN (NEW.FONCTION = 'DIRECTEUR')

BEGIN
 
   IF INSERTING THEN
      :NEW.COMMISSION := 0;
   ELSE
      IF :OLD.COMMISSION IS NULL THEN
         :NEW.COMMISSION := 0;
      ELSE
         :NEW.COMMISSION :=(:NEW.SALAIRE / :OLD.SALAIRE);
     END IF; 
  END IF;

END;
/
