-- tlog.sql
CREATE OR REPLACE TRIGGER tlog
AFTER INSERT OR UPDATE ON EMPLOYE

BEGIN
  
   INSERT INTO AUDIT_TABLE 
   VALUES ('EMPLOYE', SYSDATE, sys_context('USERENV', 'CURRENT_USER'), 'INSERT/UPDATE ON EMPLOYE');
END;
/
